name: 'CHANGE ME'
description: 'CHANGE ME'
author: 'CHANGE ME'
branding:
  icon: box
  color: blue
inputs:
  token:
    description: 'A GitHub access token'
    required: true
    default: ${{ github.token }}
  stringInput:
    description: 'A string'
  yamlInput:
    description: 'An yaml object'
runs:
  using: 'node20'
  main: 'dist/index.js'
