name: Build Action

on:
  push:
    branches: ['**'] 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: qoomon/actions--setup-git-user@v1

      # build the action
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - run: npm run build

      # commit and push changes
      - run: git add -f dist/
      - uses: JH-JDS/actions--commit@v1
        with:
          message: 'chore: build action'
          skip-empty: true
      - run: git push
